// User Management
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

// Errors
export const SET_ERRORS = 'GET_ERRORS';

// Phone Books
export const GET_PHONE_BOOKS = 'GET_PHONE_BOOKS';
export const GET_PHONE_BOOK_WITH_ENTRIES = 'GET_PHONE_BOOK_WITH_ENTRIES';
export const UPDATE_PHONE_BOOK = 'UPDATE_PHONE_BOOK';
export const CREATE_PHONE_BOOK = 'CREATE_PHONE_BOOK';
export const DELETE_PHONE_BOOK = 'DELETE_PHONE_BOOK';

// Phone Book Entries
export const GET_PHONE_BOOK_ENTRY = 'GET_PHONE_BOOK_ENTRY';
export const UPDATE_PHONE_BOOK_ENTRY = 'UPDATE_PHONE_BOOK_ENTRY';
export const CREATE_PHONE_BOOK_ENTRY = 'CREATE_PHONE_BOOK_ENTRY';
export const DELETE_PHONE_BOOK_ENTRY = 'DELETE_PHONE_BOOK_ENTRY';

